name: pace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - xarray
  - cartopy
  - earthaccess
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - typing-extensions  # Just in case for Tuple, Union typing compatibility
